[workspace]
members = ["domain", "domain-core", "domain-resolv", "domain-sign", "domain-tsig", "domain-validate", "interop"]

[patch.crates-io]
ring = { git="https://github.com/partim/ring.git", branch="ecdsa-keypair-private-key-unchecked" }

